package app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import app._0_eventsOddsDownloader.EventsOddsDownloaderModel;
import app._0_eventsOddsDownloader.model.BetBean;
import app.user.User;
import app.user.UserRepository;

@Controller    					// This means that this class is a Controller
@RequestMapping(path="/api2") 	// This means URL's start with /demo (after Application path)
public class FacadeController {
	@Autowired 					// This means to get the bean called userRepository
	           					// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private EventsOddsDownloaderModel eventsOddsDownloader;
	
    @RequestMapping(value = "/eventsOddsDownloader", method = RequestMethod.GET)
    public @ResponseBody BetBean eventsOddsDownloader () {
		
    	BetBean betBean = eventsOddsDownloader.execute();
//    	BetBean betBean = null;
		return betBean;
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}