package app.utils;

public enum RankCritEnum {
	POINTS, 
	HEAD_TO_HEAD_POINTS, 
	HEAD_TO_HEAD_GOALS_DIFFERENCE, 
	HEAD_TO_HEAD_GOALS_SCORED_AWAY, 
	MATCHES_WON, 
	GOALS_SCORED, 
	GOALS_TAKEN, 
	GOALS_DIFFERENCE,
	GOALS_SCORED_AWAY, 
	MATCHES_WON_AWAY, 
	
	
}
